buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.3.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.10"
        classpath "org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.2.10"
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
